# a=12
# sum=0
# while a<=421:
#     #   num=int(input("enter the number:"))
#     sum=sum+a
#     print(sum,a)
#     a=a+1




# i=0
# while i<100:
#     i+=1
#     if  i==10 or i==20 or i==30:
#       continue
#     # i+=1
#     print(i)
    

          ## prime numbar
# a=1
# while a<=100:
#      if a%2!=0 and a%3!=0 and a%5!=0 and a%7!=0:
#          print("its prime number",a)
#      elif a==2 or a==3 or a==5 or a==7:
#          print("its prime number",a)
#      else:
#          print("not a prime number",a)
#      a+=1



     
         # print the 20 to 100 in 2 divisibel number#


# a=20
# while a<=100:
#     if a%2==0:
#         print(a)
#     a+=


# num=int(input("enter the number:"))
# a=1
# while a<11:
#     print(num,"x",a,"=",num*a)
#     a+=1
 

# a=0
# while a<=100:
#     if a%7==0:
#       print(a)
#     a+=1



# a=30
# sum=0
# while a<=420:
#   sum=sum+a
#   if a%8==0:
#     print(a)
#     sum=sum+a
#   a+=1


          #guessing game
# a=1
# while a<=5:
#       num=int(input("enter the number:"))
#       if a==5:
#             print("congrachuretion,you win")
#             break
#       else:
#          print("you loss")
#          print(5-a, "chance remain")
#          print("try again")
#       a+=1



            #  multiply those number
# a=1
# while a<11:
#     if a%1:
#         print(a)  
    # elif a*2:
    #     print(a)
    # elif a==3:
    #     print(a*3)
    # elif a==4:
    #     print(a*4)
    # elif a==5:
    #     print(a*5)
    # elif a==6:
    #     print(a*6)
    # elif a==7:
    #     print(a*7)
    # elif a==8:
    #     print(a*8)
    # elif a==9:
    #     print(a*10)
    # a+=1


# a=int(input("enter the number"))
# i=0
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1



#                 tebel 1 to 10

# a=1
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1
# a=2
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1

# a=3
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1 

# a=4
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1 

# a=5
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1 

# a=6
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i) 
#     i+=1       
 
# a=7
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1

# a=8
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1

# a=9
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1

# a=10
# i=1
# while i<11:
#     print(a,"x",i,"=",a*i)
#     i+=1


# i=156
# while i<256:
#     z=i-155
#     print(z)
#     i=i+1

# i=156
# while i>56:
#     z=i-56
#     print(z)
#     i=i-1






# a=5
# b=10
# c=a
# print(a,b)

# brith=int(input("enter the year:"))
# currnt=int(input("enter the year"))
# if brith<currnt:
#     print(currnt-brith,"year")
# # elif brith<currnt:
# #     print(brith-currnt,"year")
# else:
#     print(brith==currnt,"equal")
    
# a=int(input("enter the number")) 
# i=1
# while i<=10:
#     if a*i:
#         print(i)
#     i+=1
    
# a=int(input("enter the number")) 
# i=1
# while i<=10:
#         print(i)
#     i+=1